# Generated by Django 4.2 on 2024-12-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airways_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phone',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='default_password', max_length=50),
        ),
    ]
