# Generated by Django 4.2 on 2024-12-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airways_app', '0002_rename_phone_register_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
